# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Medilog' do
  use_frameworks!
 
    pod 'Unbox'
    pod 'Toaster'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SlideMenuControllerSwift'

end
